config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/create'

  get 'password_resets/edit'

  get 'password_resets/update'

  resources :messages do
    get :autocomplete_user_full_name, on: :collection
  end

  resources :jobs do
    get :autocomplete_user_full_name, on: :collection
  end
  
  resources :user_sessions
  resources :messages
  resources :users
  resources :companies
  resources :jobs
  resources :timesheets
  resources :pay_periods, only: :update
  resources :password_resets

  get "login" => "user_sessions#new", as: :login
  get "logout" => "user_sessions#destroy", as: :logout

  get "/approve_timesheet" => "timesheets#toggle_approved",
    as: "approve_timesheet"

  get "/change_user_active_status" => "users#change_active_status",
    as: "change_user_active_status"

  get "/change_job_active_status" => "jobs#change_active_status",
    as: "change_job_active_status"

  get "/change_company_active_status" => "companies#change_active_status",
    as: "change_company_active_status"

  root to: "pages#home"
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :sender, class_name: "User", optional: true
  belongs_to :recipient, class_name: "User", optional: true
  enum read_status: [:unread, :read]
  after_initialize :set_default_read_status, if: :new_record?

  def set_default_read_status
    self.read_status ||= :unread
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :require_login
  before_action :set_message, only: [:show, :edit, :update, :destroy]
  before_action :set_referer, only: [:destroy, :edit, :new, :show]
  before_action :set_companies_array, only: [:new, :edit]
  after_action :verify_authorized, except: [:autocomplete_user_full_name]

  autocomplete :user, :full_name, full: true

  attr_accessor :message, :sent_messages, :rcvd_messages, :companies_array
  helper_method :message, :sent_messages, :rcvd_messages, :companies_array

  def index
    @sent_messages = current_user.sent_messages
      .order("updated_at asc")
      .paginate(page: params[:page], per_page: 10)
    @rcvd_messages = current_user.received_messages
      .order("updated_at asc")
      .paginate(page: params[:page], per_page: 10)
    authorize sent_messages
  end

  def new
    @message = Message.new
    authorize message
  end

  def show
  end

  def edit
  end

  def create
    @message = Message.new(message_params)
    authorize message
    @message.sender = current_user

    if @message.valid?
      @message.save
      redirect_to(session.delete(:return_to) || messages_path,
        notice: "Message sent successfully")
    else
      flash[:error] = @message.errors.full_messages.to_sentence
      redirect_to(session.delete(:return_to) || messages_path)
    end
  end

  def update
  end

  def destroy
  end

  def get_autocomplete_items(parameters)
    authorize Message, :is_an_admin?
    items = active_record_get_autocomplete_items(parameters)
    items.where(active_status: :active).where(
      profileable_type: "EmployeeProfile")
  end

  private
    def set_message
      @message = Message.find(params.require(:id))
      authorize message
    end

    def set_companies_array
      @companies_array = current_user.profileable.companies.all.collect {|c|
      [c.title, AdminProfile.find(c.admin_profile_id).user.id]
      } unless current_user.is_an_admin?
    end

    def message_params
      params.require(:message).permit(:recipient_id, :subject, :content)
    end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_form.html.erb
<%= bootstrap_form_for(message) do |f| %>

  <% if message.errors.any? %>
    <div id="error_explanation">
      <p>
        <%= pluralize(message.errors.count, "error") %> prohibited this message
        from being sent:
      </p>

      <ul>
      <% message.errors.full_messages.each do |error_message| %>
        <li><%= error_message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <% if current_user.is_an_admin? %>
    <%= f.label :user_full_name, "Employee Name",
      class: "control-label" %>
    <%= f.hidden_field :recipient_id, id: "the_user_id",
      value: params[:recipient_id] %>

    <% if params[:recipient_id] %>
      <% autocomplete_value = User.find(params[:recipient_id]).full_name %>
    <% else %>
      <% autocomplete_value = "" %>
    <% end %>

    <%= f.autocomplete_field :user, autocomplete_user_full_name_messages_path,
      "data-auto-focus": true, id_element: "#the_user_id",
      value: autocomplete_value, class: "form-control message-fields",
      id: "employee-name-field", required: true %>

    <div class="instruction-text" id="message-autocomplete-instruction">
      Select the employee's name as it appears while typing
    </div>
  <% else %>
    <%= f.select :recipient_id, options_for_select(companies_array,
      params[:recipient_id]), label: "Company name" %>

    <div class="instruction-text">
      Select the name of the company whose manager you want to contact.
    </div>
  <% end %>

  <br><br>

  <%= f.text_field :subject, class: "message-fields" %>

  <%= f.text_area :content, label: "Message", class: "message-fields",
    required: true %>

  <%= f.submit "Send Message", class: "btn btn-default btn-primary",
      id: "submit_message" %>
<% end %>

app/views/messages/_message.html.erb
<div class="css_cell">
  <% if show_sent %>
    <%= message.recipient.full_name %>
  <% else %>
    <%= message.sender.full_name %>
  <% end %>
</div>
<div class="css_cell">
  <%= message.created_at.strftime("%m/%d/%Y, %l:%M %p") %>
</div>
<div class="css_cell">
  <%= link_to message.subject, message_path(message) %>
</div>

app/views/messages/_messages_table.html.erb
<%= render partial: "messages_table_header", locals: {show_sent: show_sent,
  message: message} %>
<% messages.each do |message| %>
  <% if message.unread? && !show_sent %>
    <div class="css_row alert-danger">
  <% else %>
    <div class="css_row">
  <% end %>
    <%= render partial: "message", locals: {show_sent: show_sent,
      message: message} %>
  </div>
  <hr>
<% end %>

app/views/messages/_messages_table_header.html.erb
<div class="css_row">
  <div class="css_cell css_title_cell bg-info">
    <% if show_sent %>
      Recipient
    <% else %>
      Sender
    <% end %>
  </div>
  <div class="css_cell css_title_cell bg-info">
    Sent
  </div>
  <div class="css_cell css_title_cell bg-info">
    Subject
  </div>
</div>

app/views/messages/edit.html.erb
<% provide(:title, "Edit Message") %>

<h1>Edit Message</h1>

<%= render "form" %>

<br>

<%= link_to messages_path, class: "btn btn-primary back-button" do %>
  <span class="glyphicon glyphicon-chevron-left"></span> Back to Messages
<% end %>

app/views/messages/index.html.erb
<% provide(:title, "Messages") %>

<% if current_user.is_an_admin? %>
  <% message_link_text = "Send Message to Employee" %>
<% else %>
  <% message_link_text = "Send Message to the Manager" %>
<% end %>

<div id="messages_wrapper">
  <div class="panel panel-default">
    <div class="panel-body">
      <div id="new-message-button-wrapper">
        <div class="btn-group">
          <%= link_to message_link_text, new_message_path,
            class: "btn btn-success" %>
        </div>
      </div>
      <br>
      <div id="messages-tabs-container">
        <ul class="nav nav-tabs">
          <li class="active">
            <a data-toggle="tab" href="#rcvd-tab">Received Messages</a>
          </li>
          <li>
            <a data-toggle="tab" href="#sent-tab">Sent Messages</a>
          </li>
        </ul>

        <div class="tab-content">
          <div id="rcvd-tab" class="tab-pane fade in active">
            <div class="css_table">
              <div class="css_tbody">
                <%= render partial: "messages_table",
                  locals: {messages: rcvd_messages, show_sent: false} %>
              </div>

              <div class="center pagination_primary">
                <%= will_paginate rcvd_messages %>
              </div>
            </div>
          </div>
          <div id="sent-tab" class="tab-pane fade">
            <div class="css_table">
              <div class="css_tbody">
                <%= render partial: "messages_table",
                  locals: {messages: sent_messages, show_sent: true} %>
              </div>

              <div class="center pagination_primary">
                <%= will_paginate sent_messages %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/messages/new.html.erb
<% provide(:title, "New Message") %>

<div class="form_wrapper" id="new-message-panel">
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h4>
        <% if current_user.is_an_admin? %>
          Send new message to employee
        <% else %>
          Send new message to the manager
        <% end %>
      </h4>
    </div>
    <div class="panel-body">
      <%= render "form" %>
    </div>
  </div>
</div>

app/views/messages/show.html.erb
<% provide(:title, "View Message") %>

<div id="message_wrapper">
  <div class="panel panel-default">
    <div class="panel-body">
      <div id="message-container">
        <% message.read! if current_user == message.recipient %>

        <h5>
          <span class="label label-info">From:</span>
          <%= message.sender.full_name %>
        </h5>

        <h5>
          <span class="label label-info">To:</span>
          <%= message.recipient.full_name %>
        </h5>

        <h5>
          <span class="label label-info">Subject:</span>
          <%= message.subject %>
        </h5>

        <h4 id="message-content">
          <%= message.content %>
        </h4>

        <div id="message-show-buttons-container">
          <div id="messages-return-button-container">
            <%= link_to messages_path, class: "btn btn-primary" do %>
              <span class="glyphicon glyphicon-arrow-left"></span>
              Return to Messages
            <% end %>
          </div>

          <% if current_user == message.recipient %>
            <div id="message-reply-button-container">
              <%= link_to "Reply",
                new_message_path(recipient_id: message.sender_id),
                class: "btn btn-success" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>