config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/create'

  get 'password_resets/edit'

  get 'password_resets/update'

  resources :messages do
    get :autocomplete_user_full_name, on: :collection
  end

  resources :jobs do
    get :autocomplete_user_full_name, on: :collection
  end
  
  resources :user_sessions
  resources :messages
  resources :users
  resources :companies
  resources :jobs
  resources :timesheets
  resources :pay_periods, only: :update
  resources :password_resets

  get "login" => "user_sessions#new", as: :login
  get "logout" => "user_sessions#destroy", as: :logout

  get "/approve_timesheet" => "timesheets#toggle_approved",
    as: "approve_timesheet"

  get "/change_user_active_status" => "users#change_active_status",
    as: "change_user_active_status"

  get "/change_job_active_status" => "jobs#change_active_status",
    as: "change_job_active_status"

  get "/change_company_active_status" => "companies#change_active_status",
    as: "change_company_active_status"

  root to: "pages#home"
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :employee_profile, optional: true
  belongs_to :company, optional: true
  has_many :pay_periods
  enum pay_freq: [:biweekly, :monthly]
  enum active_status: [:active, :inactive]
  enum pay_type: [:wage, :shift]
  monetize :pay_cents
  after_initialize :set_default_active_status, if: :new_record?

  def children?
    pay_periods.any?
  end

  def self.archive_employee_jobs(employee_profile_id)
    Job.where("employee_profile_id = ?", employee_profile_id).each do |job|
      job.inactive!
    end
  end

  def self.archive_company_jobs(company_id)
    Job.where("company_id = ?", company_id).each do |job|
      job.inactive!
    end
  end

  def set_default_active_status
    self.active_status ||= :active
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :require_login
  before_action :set_job, only: [:edit, :update, :destroy, :show]
  before_action :set_company, only: [:new, :index]
  before_action :set_referer, only: [:destroy, :edit, :new]
  after_action :verify_authorized

  autocomplete :user, :full_name, full: true

  attr_accessor :job, :jobs, :company
  helper_method :job, :jobs, :company

  def index
    if params[:show_inactive]
      @jobs = Job.where(company_id: params.require(:company_id))
        .where(active_status: :inactive)
        .joins(employee_profile: :user)
        .order("last_name ASC, first_name ASC")
        .includes(:pay_periods, employee_profile: :user)
        .paginate(page: params[:page])
    else
      @jobs = Job.where(company_id: params.require(:company_id))
        .where(active_status: :active)
        .joins(employee_profile: :user)
        .order("last_name ASC, first_name ASC")
        .includes(:pay_periods, employee_profile: :user)
        .paginate(page: params[:page])
    end
    authorize jobs
  end

  def new
    @job = Job.new
    authorize job
  end

  def show
  end

  def edit
  end

  def create
    @job = Job.new(job_params)
    user_id = params.require(:job).permit(:user_id)[:user_id]
    company_id = params.require(:job).permit(:company_id)[:company_id]
    @job.employee_profile_id = User.find(user_id).profileable_id
    authorize job

    if @job.valid?
      @job.save
      job.employee_profile.add_company_to_self(Company.find(company_id))
      redirect_to(session.delete(:return_to) || jobs_path,
        notice: "Job created successfully")
    else
      flash[:error] = @job.errors.full_messages.to_sentence
      redirect_to(session.delete(:return_to) || jobs_path)
    end
  end

  def update
    user_id = params.require(:job).permit(:user_id)[:user_id]
    company_id = params.require(:job).permit(:company_id)[:company_id]
    employee_profile_id = User.find(user_id).profileable_id
    if @job.valid?
      @job.assign_attributes( job_params.merge(
        company_id: company_id, employee_profile_id: employee_profile_id) )
      update_assoc_on_changed_emp
      @job.save
      flash[:success] = "Job updated successfully"
      redirect_to jobs_path(company_id: job.company_id)
    else
      redirect_to jobs_path(company_id: job.company_id),
        error: "Job update failed"
    end
  end

  def update_assoc_on_changed_emp
    return unless job.employee_profile_id_changed?
    job.employee_profile.add_company_to_self(job.company)
    prev_employee_profile = EmployeeProfile.find(job.employee_profile_id_was)
    if prev_employee_profile.only_job_at_company?(job.company)
      prev_employee_profile.remove_company_from_self(job.company)
    end
  end

  def destroy
    if job.employee_profile.only_job_at_company?(job.company)
      job.employee_profile.remove_company_from_self(job.company)
    end
    job.destroy
    redirect_to jobs_path(company_id: job.company_id), notice: "Job deleted"
  end

  def change_active_status
    job = Job.find( params.require(:job_id) )
    authorize job
    if job.active?
      job.inactive!
      flash[:success] = "#{job.employee_profile.user.full_name}'s job" +
      " as #{job.title} was archived"
    else
      job.active!
      job.employee_profile.user.active!
      flash[:success] = "#{job.employee_profile.user.full_name}'s job" +
      " as #{job.title} was made active again"
    end
    redirect_to jobs_path(company_id: job.company_id)
  end

  def get_autocomplete_items(parameters)
    authorize Job, :is_an_admin?
    items = active_record_get_autocomplete_items(parameters)
    items.where(profileable_type: "EmployeeProfile")
  end

  private
    def set_job
      @job = Job.find(params.require(:id))
      authorize job
    end

    def set_company
      @company = Company.find(params.require(:company_id))
    end

    def job_params
      params.require(:job).permit(:pay, :pay_type, :employee_profile_id,
        :company_id, :title, :pay_freq)
    end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<%= bootstrap_form_for(job) do |f| %>

  <% if job.errors.any? %>
    <div id="error_explanation">
      <p>
        <%= pluralize(job.errors.count, "error") %> prohibited this job
        from being saved:
      </p>

      <ul>
      <% job.errors.full_messages.each do |error_message| %>
        <li><%= error_message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.text_field :title, value: (job.title || params[:title]),
    class: "job-fields", required: true %>

  <% if params[:user_id] %>
    <% autocomplete_value = User.find(params[:user_id]).full_name %>
    <% user_id_value = params[:user_id] %>
  <% elsif job.employee_profile_id %>
    <% user_id_value = job.employee_profile.user.id %>
    <% autocomplete_value = User.find(user_id_value).full_name %>
  <% else %>
    <% autocomplete_value = "" %>
    <% user_id_value = params[:user_id] %>
  <% end %>

  <%= f.label :user_full_name, "Employee Name", class: "control-label" %>
  <%= f.hidden_field :user_id, id: "the_user_id",
    value: user_id_value %>

  <%= f.autocomplete_field :user, autocomplete_user_full_name_jobs_path,
    "data-auto-focus": true, id_element: "#the_user_id",
    value: autocomplete_value, class: "form-control job-fields",
    id: "employee-name-job-field", required: true %>

  <div class="instruction-text" id="job-autocomplete-instruction">
    Select the employee's name as it appears while typing
  </div>

  <%= f.text_field :pay, value: (humanized_money job.pay || params[:pay]),
    label_class: "top-offset-label", id: "pay-field", class: "job-fields" %>

  <div class="instruction-text">E.g. 11.25</div>

  <%= f.select :pay_type, ["wage", "shift"], label: "Pay Type",
    selected: (job.pay_type || params[:pay_type]),
    label_class: "top-offset-label", class: "job-fields" %>

  <% unless job.children? %>
    <%= f.select :pay_freq, ["biweekly", "monthly"],
      selected: (job.pay_freq || params[:pay_freq]), label: "Pay Frequency",
      class: "job-fields" %>
  <% end %>

  <%= f.hidden_field :company_id,
    value: (job.company_id || params[:company_id]) %>

  <%= f.submit "Submit Job", class: "btn btn-default btn-primary",
      id: "submit_job" %>
<% end %>

app/views/jobs/_job.html.erb
<div class="css_cell">
  <strong><%= job.title %></strong>
</div>
<div class="css_cell">
  <span class="glyphicon glyphicon-minus" aria-hidden="true"></span>
</div>
<div class="css_cell">
  <%= job.employee_profile.user.full_name %>
</div>
<div class="css_cell">
  <span class="glyphicon glyphicon-minus" aria-hidden="true"></span>
</div>
<div class="css_cell">
  <div class="btn-group">
    <%= link_to("Timesheets", timesheets_path(job_id: job.id),
      class: "btn btn-primary") %>
  </div>
</div>
<div class="css_cell">
  <span class="glyphicon glyphicon-minus" aria-hidden="true"></span>
</div>
<div class="css_cell">
  <% if job.active? %>
    <% archive_button_text = "Archive Job" %>
    <% archive_button_class = "btn btn-warning" %>
  <% else %>
    <% archive_button_text = "Reactivate Job" %>
    <% archive_button_class = "btn btn-success" %>
  <% end %>
    <%= link_to(archive_button_text,
      change_job_active_status_path(job_id: job.id),
      data: { confirm: "Are you sure you want to change the status of" +
      " this job?" },
      class: archive_button_class) %>
</div>
<div class="css_cell">
  <div class="btn-group">
    <%= link_to("Edit Job", edit_job_path(job),
      class: "btn btn-info") %>
  </div>
</div>

<% unless job.children? %>
  <div class="css_cell">
    <div class="btn-group">
      <%= link_to("Delete Job", job_path(job.to_param,
        company_id: params[:company_id]),
        data: { :confirm => "Are you sure you want to delete this job?" },
        method: :delete, class: "btn btn-danger") %>
    </div>
  </div>
<% end %>

app/views/jobs/edit.html.erb
<% provide(:title, "Edit Job") %>

<div class="form_wrapper job-form-panel">
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h4>
        Edit Job
      </h4>
    </div>
    <div class="panel-body">
      <%= render "form" %>

      <br>
      <%= link_to jobs_path(company_id: job.company_id),
        class: "btn btn-primary back-button" do %>
        <span class="glyphicon glyphicon-chevron-left"></span> Back to Jobs
      <% end %>
    </div>
  </div>
</div>

app/views/jobs/index.html.erb
<% provide(:title, "Jobs") %>

<div id="jobs-wrapper">
  <div class="panel panel-primary inline-panel">
    <div class="panel-heading">
      <h3 class="panel-title"><%= company.title %> Jobs</h3>
    </div>

    <div id="new-archived-job-buttons-wrapper">
      <div id="new-job-button-wrapper">
        <div class="btn-group">
          <%= link_to "New Job", new_job_path(company_id: params[:company_id]),
            class: "btn btn-success",
            id: "new_job_button", method: :get %>
        </div>
      </div>

      <div id="archived-jobs-button">
        <% if params[:show_inactive] %>
          <%= link_to "Show Active Jobs",
            jobs_path(company_id: params[:company_id]),
            class: "btn btn-primary", id: "show_active_jobs_button",
            method: :get %>
        <% else %>
          <%= link_to "Show Archived Jobs",
            jobs_path(company_id: params[:company_id], show_inactive: true),
            class: "btn btn-warning", id: "show_inactive_jobs_button",
            method: :get %>
        <% end %>
      </div>
    </div>

    <hr class="horizontal-line" />

    <div class="css_table" id="jobs-table">
      <div class="css_tbody">
        <% jobs.each do |job| %>
          <div class="css_row">
            <%= render job %>
          </div>
          <hr>
        <% end %>
      </div>
    </div>
    <div class="center pagination_primary">
      <%= will_paginate jobs %>
    </div>
  </div>
</div>

app/views/jobs/new.html.erb
<% provide(:title, "New Job") %>

<div class="form_wrapper job-form-panel">
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h4>
        New Job
      </h4>
    </div>
    <div class="panel-body">
      <%= render "form" %>

      <br>
      <%= link_to jobs_path(company_id: params[:company_id]),
        class: "btn btn-primary back-button" do %>
        <span class="glyphicon glyphicon-chevron-left"></span> Back to Jobs
      <% end %>
    </div>
  </div>
</div>