config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/create'

  get 'password_resets/edit'

  get 'password_resets/update'

  resources :messages do
    get :autocomplete_user_full_name, on: :collection
  end

  resources :jobs do
    get :autocomplete_user_full_name, on: :collection
  end
  
  resources :user_sessions
  resources :messages
  resources :users
  resources :companies
  resources :jobs
  resources :timesheets
  resources :pay_periods, only: :update
  resources :password_resets

  get "login" => "user_sessions#new", as: :login
  get "logout" => "user_sessions#destroy", as: :logout

  get "/approve_timesheet" => "timesheets#toggle_approved",
    as: "approve_timesheet"

  get "/change_user_active_status" => "users#change_active_status",
    as: "change_user_active_status"

  get "/change_job_active_status" => "jobs#change_active_status",
    as: "change_job_active_status"

  get "/change_company_active_status" => "companies#change_active_status",
    as: "change_company_active_status"

  root to: "pages#home"
end

app/models/company.rb
class Company < ApplicationRecord
  belongs_to :admin_profile, optional: true
  has_many :jobs
  has_and_belongs_to_many :employee_profiles
  enum active_status: [:active, :inactive]
  after_initialize :set_default_active_status, if: :new_record?

  def children?
    employee_profiles.any? || jobs.any?
  end

  def set_default_active_status
    self.active_status ||= :active
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :require_login
  before_action :set_company, only: [:edit, :update, :destroy, :show]
  before_action :set_referer, only: [:destroy, :edit, :new]
  before_action :set_admin_array, only: [:new, :edit]
  after_action :verify_authorized

  attr_accessor :company, :companies, :admin_array
  helper_method :company, :companies, :admin_array

  def index
    if params[:show_inactive]
      @companies = Company.where(active_status: :inactive)
        .order("title ASC")
        .includes(:employee_profiles)
        .paginate(page: params[:page])
    else
      @companies = Company.where(active_status: :active)
        .order("title ASC")
        .includes(:employee_profiles)
        .paginate(page: params[:page])
    end
    authorize companies
  end

  def new
    @company = Company.new
    authorize company
  end

  def show
  end

  def edit
  end

  def create
    @company = Company.new(company_params)
    authorize company

    if @company.valid?
      @company.save
      redirect_to(session.delete(:return_to) || companies_path,
        notice: "Company created successfully")
    else
      flash[:error] = @company.errors.full_messages.to_sentence
      redirect_to(session.delete(:return_to) || companies_path)
    end
  end

  def update
    if @company.update(company_params)
      flash[:success] = "Company updated successfully"
      redirect_to companies_path
    else
      redirect_to companies_path, error: "Company update failed"
    end
  end

  def destroy
    company.destroy
    redirect_to companies_path, notice: "#{company.title} was deleted"
  end

  def change_active_status
    company = Company.find( params.require(:company_id) )
    authorize company
    if company.active?
      company.inactive!
      Job.archive_company_jobs(company.id)
      flash[:success] = "#{company.title} was archived"
    else
      company.active!
      flash[:success] = "#{company.title} was made active again"
    end
    redirect_to companies_path
  end

  private
    def set_company
      @company = Company.find(params.require(:id))
      authorize company
    end

    def set_admin_array
      @admin_array = AdminProfile.all.includes(:user).collect do |a|
        [a.user.full_name, a.id]
      end
    end

    def company_params
      params.require(:company).permit(:admin_profile_id, :title)
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_company.html.erb
<div class="css_cell">
  <strong>
    <%= link_to(company.title, jobs_path(company_id: company.id)) %>
  </strong>
</div>
<div class="css_cell">
  <span class="glyphicon glyphicon-minus" aria-hidden="true"></span>
</div>
<div class="css_cell">
  <% if company.active? %>
    <% archive_button_text = "Archive Company" %>
    <% archive_button_class = "btn btn-warning" %>
  <% else %>
    <% archive_button_text = "Reactivate Company" %>
    <% archive_button_class = "btn btn-success" %>
  <% end %>
    <%= link_to(archive_button_text,
      change_company_active_status_path(company_id: company.id),
      data: { confirm: "Are you sure you want to change the status of" +
      " #{company.title}?" },
      class: archive_button_class) %>
</div>
<div class="css_cell">
  <div class="btn-group">
    <%= link_to("Edit Company", edit_company_path(company),
      class: "btn btn-info") %>
  </div>
</div>

<% unless company.children? %>
  <div class="css_cell">
    <div class="btn-group">
      <%= link_to("Delete Company", company_path(company),
        data: { :confirm => "Are you sure you want to delete this company?" },
        method: :delete, class: "btn btn-danger") %>
    </div>
  </div>
<% end %>

app/views/companies/_form.html.erb
<%= bootstrap_form_for(company) do |f| %>

  <% if company.errors.any? %>
    <div id="error_explanation">
      <p>
        <%= pluralize(company.errors.count, "error") %> prohibited this company
        from being saved:
      </p>

      <ul>
      <% company.errors.full_messages.each do |error_message| %>
        <li><%= error_message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.text_field :title, class: "company-fields", required: true %>

  <%= f.select :admin_profile_id, options_for_select(admin_array,
    params[:admin_profile_id]), label: "Administrator name",
    class: "company-fields" %>

  <div class="instruction-text">
    Select the name of the person to be the Administrator of this company.
    If they are not a registered user yet, you must first
    <%= link_to "create their user account", new_user_path %>.
  </div>

  <br><br>

  <%= f.submit "Submit Company", class: "btn btn-default btn-primary",
      id: "submit_company" %>
<% end %>

app/views/companies/edit.html.erb
<% provide(:title, "Edit Company") %>

<div class="form_wrapper company-form-panel">
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h4>
        Edit Company
      </h4>
    </div>
    <div class="panel-body">
      <%= render "form" %>

      <br>
      <%= link_to companies_path, class: "btn btn-primary back-button" do %>
        <span class="glyphicon glyphicon-chevron-left"></span> Back to Companies
      <% end %>
    </div>
  </div>
</div>

app/views/companies/index.html.erb
<% provide(:title, "Companies") %>

<div id="companies-wrapper">
  <div class="panel panel-primary inline-panel">
    <div class="panel-heading">
      <h3 class="panel-title">Companies</h3>
    </div>

    <div id="new-archived-companies-buttons-wrapper">
      <div id="new-company-button-wrapper">
        <%= link_to "New Company", new_company_path, class: "btn btn-success",
          id: "new_company_button", method: :get %>
      </div>

      <div id="archived-companies-button">
        <% if params[:show_inactive] %>
          <%= link_to "Show Active Companies", companies_path,
            class: "btn btn-primary", id: "show_active_companies_button",
            method: :get %>
        <% else %>
          <%= link_to "Show Archived Companies",
            companies_path(show_inactive: true), class: "btn btn-warning",
            id: "show_inactive_companies_button", method: :get %>
        <% end %>
      </div>
    </div>

    <hr class="horizontal-line" />

    <div class="css_table" id="companies-table">
      <div class="css_tbody">
        <% companies.each do |company| %>
          <div class="css_row">
            <%= render company %>
          </div>
          <hr>
        <% end %>
      </div>
    </div>
    <div class="center pagination_primary">
      <%= will_paginate companies %>
    </div>
  </div>
</div>

app/views/companies/new.html.erb
<% provide(:title, "New Company") %>

<div class="form_wrapper company-form-panel">
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h4>
        New Company
      </h4>
    </div>
    <div class="panel-body">
      <%= render "form" %>

      <br>
      <%= link_to companies_path, class: "btn btn-primary back-button" do %>
        <span class="glyphicon glyphicon-chevron-left"></span> Back to Companies
      <% end %>
    </div>
  </div>
</div>

app/views/companies/show.html.erb
<% provide(:title, company.title) %>

<h4>
  <%= company.title %>
</h4>

<div class="btn-group">
  <%= link_to("Jobs", jobs_path(company_id: company.id),
    class: "btn btn-info") %>
</div>