config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/create'

  get 'password_resets/edit'

  get 'password_resets/update'

  resources :messages do
    get :autocomplete_user_full_name, on: :collection
  end

  resources :jobs do
    get :autocomplete_user_full_name, on: :collection
  end
  
  resources :user_sessions
  resources :messages
  resources :users
  resources :companies
  resources :jobs
  resources :timesheets
  resources :pay_periods, only: :update
  resources :password_resets

  get "login" => "user_sessions#new", as: :login
  get "logout" => "user_sessions#destroy", as: :logout

  get "/approve_timesheet" => "timesheets#toggle_approved",
    as: "approve_timesheet"

  get "/change_user_active_status" => "users#change_active_status",
    as: "change_user_active_status"

  get "/change_job_active_status" => "jobs#change_active_status",
    as: "change_job_active_status"

  get "/change_company_active_status" => "companies#change_active_status",
    as: "change_company_active_status"

  root to: "pages#home"
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">

    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed"
        data-toggle="collapse" data-target="#navbar-collapse-area"
        aria-expanded="false">
        <img alt="FH" src="<%= image_path("https://s3.amazonaws.com/fountainhouse-bucket/fh-logo.jpg") %>">
      </button>
      <a class="navbar-brand" id="site_title" href="<%= root_path %>">
        Timesheet Portal
      </a>
    </div>

    <div class="collapse navbar-collapse" id="navbar-collapse-area">

      <% if logged_in? && current_user.is_an_admin? %>
        <ul class="nav navbar-nav navbar-left" class="navbar-buttons">
          <%= render "layouts/my_companies_dropdown" %>
          <%= render "layouts/navbar_messages_link" %>
          <%= render "layouts/navbar_manage_users_link" %>
          <%= render "layouts/navbar_manage_companies_link" %>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <%= render "layouts/navbar_greeting" %>
        </ul>
      <% elsif logged_in? %>
        <ul class="nav navbar-nav navbar-left" class="navbar-buttons">
          <%= render "layouts/my_jobs_dropdown" %>
          <%= render "layouts/navbar_messages_link" %>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <%= render "layouts/navbar_greeting" %>
        </ul>
      <% else %>
        <ul class="nav navbar-nav navbar-right">
          <li>
            <%= link_to "Sign in", login_path %>
          </li>
        </ul>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/_my_companies_dropdown.html.erb
<li class="dropdown">
  <a href="#" class="dropdown-toggle"
    data-toggle="dropdown" role="button"
    aria-haspopup="true" aria-expanded="false">
    My Companies <span class="caret"></span>
  </a>
  <ul class="dropdown-menu">
    <% current_user_companies.each do |company| %>
      <% unless company == current_user_companies.first %>
        <li role="separator" class="divider"></li>
      <% end %>
      <li>
        <%= link_to company.title,
          jobs_path(company_id: company.id) %>
      </li>
    <% end %>
  </ul>
</li>

app/views/layouts/_my_jobs_dropdown.html.erb
<li class="dropdown">
  <a href="#" class="dropdown-toggle"
    data-toggle="dropdown" role="button"
    aria-haspopup="true" aria-expanded="false">
    My Jobs <span class="caret"></span>
  </a>
  <ul class="dropdown-menu">
    <% current_user_jobs.each do |job| %>
      <% unless job == current_user_jobs.first %>
        <li role="separator" class="divider"></li>
      <% end %>
      <li>
        <%= link_to "#{job.title} - #{job.company.title}",
          timesheets_path(job_id: job.id) %>
      </li>
    <% end %>
  </ul>
</li>

app/views/layouts/_navbar_greeting.html.erb
<li>
  <p class="navbar-text">
    Signed in as
      <%= current_user.full_name || current_user.username %>
  </p>
</li>

<li>
  <%= link_to "Sign out", logout_path %>
</li>
          

app/views/layouts/_navbar_manage_companies_link.html.erb
<li>
  <%= link_to "Company Management", companies_path %>
</li>

app/views/layouts/_navbar_manage_users_link.html.erb
<li>
  <%= link_to "User Management", users_path %>
</li>

app/views/layouts/_navbar_messages_link.html.erb
<li>
  <%= link_to messages_path do %>
    Messages
    <% if current_user.unread_message_count > 0 %>
      <span class="badge progress-bar-danger">
        <%= current_user.unread_message_count %>
      </span>
    <% end %>
  <% end %>
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield :title %> | Timesheet Portal</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  </head>

  <body>
  <%= render "layouts/header" %>

    <% flash.each do |key, value| %>
      <div class="<%= flash_class(key.to_sym) %>">
        <%= sanitize(value) %>
      </div>
    <% end %>
  
    <%= yield %>
  </body>
</html>